name: Test Flask book
on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.14
    steps:
      - name: Checkout source
        uses: actions/checkout@v6
      - name: Install python dependencies
        run: pip install pytest flask flask-restful

      - name: Run test
        run: |
          cd books/python-flask/
          perl run_tests.pl

