name: Test Flask book
on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: szabgab/python
    steps:
      - name: Checkout source
        uses: actions/checkout@v6
      - name: Run test
        run: |
          cd books/python-flask/
          perl run_tests.pl

