name: Test Flask book
on:
  push:
  workflow_dispatch:

jobs:
  flask:
    runs-on: ubuntu-latest
    container:
      image: python:3.14
    steps:
      - name: Checkout source
        uses: actions/checkout@v6
      - name: Install python dependencies
        run: pip install -r books/python-flask/requirements.txt

      - name: Run test
        run: |
          cd books/python-flask/
          perl run_tests.pl

  decorators:
    runs-on: ubuntu-latest
    container:
      image: python:3.14
    steps:
      - name: Checkout source
        uses: actions/checkout@v6
      #- name: Install python dependencies
      #  run: pip install -r books/python-decorators/requirements.txt

      - name: Run test
        run: |
          cd books/python-decorators/src/examples/decorators
          pytest

